apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=hyejiPyo/myapp
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hyejiPyo/myapp:v1.0.1
        ports:
        - containerPort: 80